[package]
name = "zk-shuffle"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-std = { version = "0.5.0", features = ["parallel"] }
ark-groth16 = "0.5.0"
ark-relations = "0.5.0"
ark-snark = "0.5.0"
ark-circom = "0.5.0"
rust-rapidsnark = "0.1.3"
babyjubjub-rs = "0.0.11"
taceo-ark-babyjubjub = "0.5.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
hex = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
ark-serialize = "0.5.0"
log = "0.4"
memmap2 = "0.9"
wasmer = "4.4"
color-eyre = "0.6"

[dev-dependencies]
rand_chacha = "0.3"
tokio = { version = "1", features = ["full"] }
