[workspace]
members = [
    "contracts/juodzekas",
    "clients/tui",
    "packages/zk-shuffle",
    "packages/blackjack",
]
resolver = "2"

[patch."https://github.com/burnt-labs/mob"]
xion-types = { git = "https://github.com/burnt-labs/xion-types" }
