[workspace]
members = [
    "contracts/juodzekas",
    "clients/tui",
    "clients/dealer",
    "packages/zk-shuffle",
    "packages/blackjack",
]
exclude = [
    "clients/tui",
    "clients/dealer",
]
resolver = "2"
